Algoritmo "hello world "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Esse programa escreve hello world
// Autor(a)    : Gabriel Alves Coelho
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis 
msg: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva ("hello world ")

Fimalgoritmo